export const INICIAR_CRONOMETRO = 'INICIAR_CRONOMETRO'
export const PARAR_CRONOMETRO = 'PARAR_CRONOMETRO'
export const FALHA_CRONOMETRO = 'FALHA_CRONOMETRO'
export const ZERAR_CRONOMETRO = 'ZERAR_CRONOMETRO'
